### ISSUE TITLE
Put it on GitHub Pages

### ISSUE THREAD

**Issue by CryZe** [jpnance/wwwsplit#2]
By putting it on GitHub Pages, GitHub automatically serves the latest version as a static webpage that anyone can access. It's kind of annoying to not be able to access it in any other way than cloning it at the moment. So that would solve it.

**Comment by jpnance** [comment]
Great suggestion! I'll try to figure out how to do this tonight.

**Comment by CryZe** [comment]
I think you just need a branch called "gh-pages". You might need to enable
it in the repository settings too.

2015-07-02 22:18 GMT+02:00 Patrick Nance notifications@github.com:

**Comment by jpnance** [comment]
Indeed! I'll need to remember to keep gh-pages relatively synced with master. I'll add a link to the README file.

http://jpnance.github.io/wwwsplit/

**Comment by CryZe** [comment]
I'd suggest using it instead of master and just delete master (you need to
select the gh-pages branch as default in the repository settings, before
being allowed to delete master). That's easier and works pretty well.

2015-07-02 22:23 GMT+02:00 Patrick Nance notifications@github.com:
